@startuml
title Inventarysoft - Package Diagram

' --- Configuración Estética ---
skinparam shadowing false
skinparam backgroundColor #FDFDFD
skinparam RoundCorner 0
skinparam defaultFontName Arial
skinparam nodesep 30
skinparam ranksep 50

' Estilo para que parezcan carpetas
skinparam packageStyle folder

skinparam package {
    BackgroundColor white
    BorderColor #2C3E50
    FontStyle bold
    FontSize 12
}

skinparam class {
    BackgroundColor #F8FAFC
    BorderColor #94A3B8
    FontSize 10
}

' --- CONTENEDOR PRINCIPAL DEL SISTEMA ---
node "Inventarysoft System" {

    ' FILA 1: Los más grandes
    together {
      package "Security Management" as Security {
        role -[hidden]right- permission
        permission -[hidden]right- role_permission
        role_permission -[hidden]down- system_module
        system_module -[hidden]right- module_permission
        module_permission -[hidden]right- person
        person -[hidden]down- user_account
      }

      package "System Parameterization" as Param {
        document_type -[hidden]right- product_category
        product_category -[hidden]right- payment_method
        payment_method -[hidden]down- inventory_movement_type
        inventory_movement_type -[hidden]right- user_role
        user_role -[hidden]right- system_status
      }
    }

    ' FILA 2: Tamaño Mediano
    together {
      package "Sales Operations" as Sales {
        sale -[hidden]right- sale_detail
        sale_detail -[hidden]down- invoice
        invoice -[hidden]right- payment
      }

      package "Product & Inventory" as Product {
        product -[hidden]right- inventory
        inventory -[hidden]down- inventory_movement
      }

      package "Customers & Services" as Customers {
        customer -[hidden]right- service
        service -[hidden]down- customer_service
      }
    }

    ' FILA 3: Los más pequeños
    together {
      package "Notifications" as Notes {
        message_template -[hidden]right- notification
        notification -[hidden]down- alert_rule
      }

      package "Human Resources" as HR {
        employee -[hidden]right- position
      }
    }
  } 
@enduml
